version: '3'
volumes:
  mysql:

services:
  php:
    build: php-image
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
  sql:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musicstream
    volumes:
      - mysql:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d
    ports:
       - "3306:3306"